### ISSUE TITLE
Restructure Events

### ISSUE THREAD

**Issue by xaviertintin** [nova-epn/landing-page#4]
https://www.novaclub.tech/eventos/
# Upcoming events

## Transcendiendo Fronteras
Countdown
_Link to Transcendiendo Fronteras event_

# All Events
- Transcendiendo Fronteras (https://www.novaclub.tech/eventos/transcendiendo-fronteras)
  - Register: https://trascendiendo-fronteras.eventbrite.com
- Networking with Experts
- Sinergia III
- Blockchain Week

**Comment by padimaster** [comment]
The events section has been implemented and is available at [Nova Events](https://www.novaclub.tech/eventos)
